import RaffleBoard from '@/components/RaffleBoard'
import Countdown from '@/components/Countdown'
import BrandHeader from '@/components/BrandHeader'
import ShareButtons from '@/components/ShareButtons'
import {adminSupabase} from '@/lib/supabase'
import {notFound} from 'next/navigation'
import type {Metadata} from 'next'
export const dynamic='force-dynamic'
async function getRaffle(slug:string){const db=adminSupabase();const {data}=await db.from('raffles').select('*').eq('slug',slug).single();return data}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params,r=await getRaffle(slug);if(!r||r.status==='draft')return {title:'Rifa no disponible',robots:{index:false,follow:false}};const desc=`${r.title} · $${(r.price_cents/100).toLocaleString('es-MX')} por número. Consulta disponibilidad y bases en Punto de Suerte.`;return {title:r.title,description:desc,openGraph:{title:`${r.title} | Punto de Suerte`,description:desc,images:r.hero_image?[{url:r.hero_image,alt:r.title}]:[]},twitter:{card:'summary_large_image',title:r.title,description:desc,images:r.hero_image?[r.hero_image]:[]}}}
export default async function Page({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const db=adminSupabase();const r=await getRaffle(slug);if(!r||r.status==='draft')notFound();
 const {data:numbers}=await db.from('raffle_numbers').select('status').eq('raffle_id',r.id);const paid=(numbers||[]).filter((n:any)=>n.status==='paid').length;const soldOut=paid>=r.total_numbers;const now=Date.now(),upcoming=!!r.opens_at&&new Date(r.opens_at).getTime()>now,expired=!!r.closes_at&&new Date(r.closes_at).getTime()<=now,closed=r.status==='closed'||expired;const active=r.status==='open'&&!upcoming&&!closed&&!soldOut;const imgs=Array.isArray(r.gallery_images)?r.gallery_images:[];
 const status=closed?'FINALIZADA':soldOut?'AGOTADA':upcoming?'PRÓXIMAMENTE':'ACTIVA';
 return <main className="wrap"><BrandHeader/><section className="hero publicHero"><div><span className="badge">{status} · {r.total_numbers} NÚMEROS</span><h1>{r.title}</h1><p className="muted">{r.description}</p><div className="price">${(r.price_cents/100).toLocaleString('es-MX')} <small>por número</small></div>{upcoming&&r.opens_at&&<><p className="muted">Apertura en:</p><Countdown target={r.opens_at}/></>}{active&&r.closes_at&&<><p className="muted">Cierre de participaciones:</p><Countdown target={r.closes_at}/></>}<ShareButtons title={r.title} price={r.price_cents/100}/></div>{r.hero_image&&<img src={r.hero_image} alt={r.title}/>}</section>
 {active?<section className="card"><h2>Elige tu número 🍀</h2><p className="muted">Selecciona uno disponible. Quedará apartado temporalmente y podrás continuar por WhatsApp.</p><RaffleBoard slug={slug}/></section>:<section className="card stateCard"><span className="badge">{status}</span><h2>{upcoming?'Esta rifa todavía no abre':soldOut?'Todos los números están ocupados':'Las participaciones están cerradas'}</h2><p className="muted">El tablero permanece visible en el avance general, pero ya no acepta nuevos apartados.</p><div className="stats"><div className="stat"><b>{paid}</b><br/><span className="muted">pagados</span></div><div className="stat"><b>{r.total_numbers}</b><br/><span className="muted">números</span></div></div></section>}
 {imgs.length>0&&<section className="card"><h2>El premio</h2><div className="gallery">{imgs.map((x:string,i:number)=><img key={i} src={x} alt={`${r.title} ${i+1}`}/>)}</div></section>}<section className="card"><h2>¿Cómo funciona?</h2><p>1. Elige un número disponible. 2. Escribe tu nombre y WhatsApp. 3. El número queda apartado temporalmente. 4. Continúa a WhatsApp para recibir instrucciones. 5. Cuando el pago es confirmado, el tablero cambia a Pagado.</p></section>{r.delivery_text&&<section className="card"><h2>Entrega del premio</h2><p className="preLine">{r.delivery_text}</p></section>}{r.terms_text&&<section className="card"><h2>Bases y condiciones</h2><p className="preLine termsText">{r.terms_text}</p></section>}</main>}
