'use client'
import {useCallback,useEffect,useMemo,useState} from 'react'
type Status='available'|'reserved'|'paid'
type Num={id:string;number:number;status:Status;reserved_until:string|null}
type Props={slug:string;testMode?:boolean}
function effective(x:Num):Status{return x.status==='reserved'&&x.reserved_until&&new Date(x.reserved_until).getTime()<=Date.now()?'available':x.status}
export default function RaffleBoard({slug,testMode=false}:Props){
 const [raffle,setRaffle]=useState<any>(null),[items,setItems]=useState<Num[]>([]),[loading,setLoading]=useState(true),[selected,setSelected]=useState<number|null>(null),[name,setName]=useState(''),[phone,setPhone]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState<any>(null);const [,tick]=useState(0)
 const load=useCallback(async()=>{const url=testMode?`/api/admin/raffles/${encodeURIComponent(slug)}`:`/api/raffles/${encodeURIComponent(slug)}`;const r=await fetch(url,{cache:'no-store'});const j=await r.json();if(j.ok){setRaffle(j.raffle);setItems(j.numbers||[])}setLoading(false)},[slug,testMode])
 useEffect(()=>{load();const t=setInterval(()=>{tick(v=>v+1);load()},10000);return()=>clearInterval(t)},[load])
 const stats=useMemo(()=>{const e=items.map(effective);return{available:e.filter(s=>s==='available').length,reserved:e.filter(s=>s==='reserved').length,paid:e.filter(s=>s==='paid').length}},[items])
 async function reserve(){if(!selected||!name.trim()||!phone.trim())return;setBusy(true);setError('');const referral=new URLSearchParams(window.location.search).get('ref')||(testMode?'prueba':'directo');try{const url=testMode?`/api/admin/raffles/${encodeURIComponent(slug)}/test/reserve`:'/api/reserve';const body=testMode?{number:selected,name,whatsapp:phone,referral}:{slug,number:selected,name,whatsapp:phone,referral};const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'No se pudo apartar');setSuccess({number:selected,until:j.reservedUntil,url:j.whatsappUrl});setSelected(null);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(loading)return <p className="muted">Cargando tablero...</p>;if(!raffle)return <div className="notice error">Rifa no disponible.</div>
 return <><div className="stats"><div className="stat"><b>{stats.available}</b><br/><span className="muted">disponibles</span></div><div className="stat"><b>{stats.reserved}</b><br/><span className="muted">apartados</span></div><div className="stat"><b>{stats.paid}</b><br/><span className="muted">pagados</span></div></div><div className="progress"><div style={{width:`${items.length?((items.length-stats.available)/items.length)*100:0}%`}}/></div><p className="muted">{items.length-stats.available} de {raffle.total_numbers} números ocupados</p><div className="grid">{items.map(x=>{const s=effective(x);return <button key={x.id} disabled={s!=='available'} onClick={()=>setSelected(x.number)} className={`num ${s}`}>{String(x.number).padStart(2,'0')}</button>})}</div><p className="muted">🟢 Disponible · 🟡 Apartado · 🔴 Pagado</p>{selected&&<div className="modal"><div className="modalBox"><h2>{testMode?'Probar apartado':'Apartar'} #{String(selected).padStart(2,'0')}</h2><p className="muted">{testMode?'Este registro será marcado como PRUEBA y podrá limpiarse antes de activar.':`Se apartará por ${raffle.reserve_minutes} minutos.`}</p><label>Nombre</label><input value={name} onChange={e=>setName(e.target.value)}/><label>WhatsApp</label><input value={phone} onChange={e=>setPhone(e.target.value)}/>{error&&<p className="notice error">{error}</p>}<div className="actions"><button className="btn" disabled={busy} onClick={reserve}>{busy?'Apartando...':testMode?'Simular apartado':'Apartar número'}</button><button className="btn secondary" onClick={()=>setSelected(null)}>Cancelar</button></div></div></div>}{success&&<div className="modal"><div className="modalBox"><span className="badge">{testMode?'PRUEBA':'¡APARTADO!'}</span><h2>El #{String(success.number).padStart(2,'0')} quedó apartado</h2><p>{testMode?'Ahora ve al panel y prueba “Confirmar pago” o “Liberar”. No se enviará a WhatsApp.':<>Vence a las <b>{new Date(success.until).toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'})}</b>.</>}</p>{!testMode&&<a className="btn" href={success.url} target="_blank">Continuar a WhatsApp</a>} <button className="btn secondary" onClick={()=>setSuccess(null)}>Cerrar</button></div></div>}</>
}
