'use client'
import {useCallback,useEffect,useMemo,useState} from 'react'
import {useParams,useRouter} from 'next/navigation'
import RafflePreview from '@/components/RafflePreview'

type P={name?:string;whatsapp?:string;referral?:string;is_test?:boolean}
type Row={id:string;number:number;status:string;reserved_until:string|null;participants:P|P[]|null}
const part=(r:Row)=>Array.isArray(r.participants)?r.participants[0]:r.participants
const money=(c:number)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(c/100)
const moneyMx=(n:number)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:2}).format(n||0)
const roundUp10=(n:number)=>Math.ceil(n/10)*10

export default function Manage(){
  const {slug}=useParams<{slug:string}>();const router=useRouter()
  const [r,setR]=useState<any>(null),[rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[copied,setCopied]=useState('')
  const [edit,setEdit]=useState<any>(null),[autoPrice,setAutoPrice]=useState(true),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[saved,setSaved]=useState(false)
  const [referrals,setReferrals]=useState<any[]>([]),[refName,setRefName]=useState(''),[refCode,setRefCode]=useState('')
  const load=useCallback(async()=>{const x=await fetch(`/api/admin/raffles/${slug}`,{cache:'no-store'});if(x.status===401){location.href='/admin';return}const j=await x.json();if(j.ok){setR(j.raffle);setRows(j.numbers||[]);setEdit((old:any)=>old||toEdit(j.raffle))}else setError(j.error)},[slug])
  const loadRefs=useCallback(async()=>{const x=await fetch(`/api/admin/raffles/${slug}/referrals`,{cache:'no-store'});if(x.ok){const j=await x.json();if(j.ok)setReferrals(j.referrals||[])}},[slug])
  useEffect(()=>{load();loadRefs();const i=setInterval(()=>{load();loadRefs()},10000);return()=>clearInterval(i)},[load,loadRefs])
  const stats=useMemo(()=>{const test=rows.filter(x=>!!part(x)?.is_test);const real=rows.filter(x=>!part(x)?.is_test);return{paid:real.filter(x=>x.status==='paid').length,reserved:real.filter(x=>x.status==='reserved').length,available:rows.filter(x=>x.status==='available').length,testPaid:test.filter(x=>x.status==='paid').length,testReserved:test.filter(x=>x.status==='reserved').length,testTotal:test.filter(x=>x.status!=='available').length}},[rows])
  const exact=edit?.total_numbers>0?Number(edit.target||0)/Number(edit.total_numbers):0
  const recommended=roundUp10(exact),projected=Number(edit?.price||0)*Number(edit?.total_numbers||0)

  function toEdit(x:any){return {title:x.title||'',slug:x.slug||'',description:x.description||'',price:(x.price_cents||0)/100,value:(x.value_cents||0)/100,target:(x.target_cents||0)/100,total_numbers:x.total_numbers||1,reserve_minutes:x.reserve_minutes||30,whatsapp:x.whatsapp||'',opens_at:x.opens_at?String(x.opens_at).slice(0,16):'',closes_at:x.closes_at?String(x.closes_at).slice(0,16):'',hero_image:x.hero_image||'',gallery_images:Array.isArray(x.gallery_images)?x.gallery_images:[],terms_text:x.terms_text||'',delivery_text:x.delivery_text||''}}
  function set(k:string,v:any){setSaved(false);const next={...edit,[k]:v};if(autoPrice&&(k==='target'||k==='total_numbers')){const target=Number(k==='target'?v:next.target)||0,total=Number(k==='total_numbers'?v:next.total_numbers)||0;if(total>0)next.price=roundUp10(target/total)}setEdit(next)}
  function toggleAuto(v:boolean){setAutoPrice(v);if(v&&Number(edit.total_numbers)>0)setEdit({...edit,price:roundUp10(Number(edit.target||0)/Number(edit.total_numbers))})}
  const checks=edit?[{label:'Título',ok:!!edit.title.trim()},{label:'URL / slug',ok:!!edit.slug.trim()},{label:'Descripción',ok:!!edit.description.trim()},{label:'Imagen principal',ok:!!edit.hero_image},{label:'Precio',ok:Number(edit.price)>0},{label:'Cantidad de números',ok:Number(edit.total_numbers)>0},{label:'Fecha de cierre',ok:!!edit.closes_at},{label:'WhatsApp',ok:!!edit.whatsapp.trim()},{label:'Bases y condiciones',ok:!!edit.terms_text.trim()}]:[]
  const hasTestData=stats.testTotal>0
  const canActivate=checks.length>0&&checks.every(x=>x.ok)&&!hasTestData

  async function action(number:number,action:string){if(!confirm(action==='paid'?'¿Confirmar pago?':'¿Liberar número?'))return;const x=await fetch(`/api/admin/raffles/${slug}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({number,action})});const j=await x.json();if(!x.ok)alert(j.error);else load()}
  async function status(s:string,startNow=false){if(s==='open'){if(r.status==='draft'&&!canActivate){alert('Completa los elementos pendientes de la checklist antes de activar.');return}if(!confirm(startNow?'¿Iniciar la rifa ahora? Se cancelará cualquier apertura programada y las reservas quedarán habilitadas inmediatamente.':'¿Activar esta rifa? Después de activarla ya no podrás editarla ni eliminarla.'))return}const x=await fetch(`/api/admin/raffles/${slug}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status:s,startNow})});const j=await x.json();if(!x.ok){alert(j.error||'Error');return}setR(j.raffle);setEdit(toEdit(j.raffle));load()}
  async function saveSchedule(){const x=await fetch(`/api/admin/raffles/${slug}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({opens_at:edit?.opens_at||null,closes_at:edit?.closes_at||null})});const j=await x.json();if(!x.ok){alert(j.error||'No se pudo guardar el horario');return}setR(j.raffle);setEdit(toEdit(j.raffle));alert('Horario actualizado. Cuando estés listo, pulsa Reabrir.')}
  async function copy(ref:string){const u=`${location.origin}/rifa/${slug}?ref=${encodeURIComponent(ref)}`;await navigator.clipboard.writeText(u);setCopied(ref);setTimeout(()=>setCopied(''),1200)}
  async function addReferral(){if(!refName.trim())return;const x=await fetch(`/api/admin/raffles/${slug}/referrals`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:refName,code:refCode})});const j=await x.json();if(!x.ok){alert(j.error||'No se pudo crear el referido');return}setRefName('');setRefCode('');loadRefs()}
  async function toggleReferral(id:string,active:boolean){await fetch(`/api/admin/raffles/${slug}/referrals`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,active})});loadRefs()}
  async function deleteReferral(id:string,name:string){if(!confirm(`¿Eliminar el enlace de ${name}? Los boletos ya registrados conservarán su origen.`))return;const x=await fetch(`/api/admin/raffles/${slug}/referrals`,{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id})});if(x.ok)loadRefs()}
  async function upload(files:FileList|null,kind:'hero'|'gallery'){if(!files?.length)return;setUploading(true);setError('');try{const fd=new FormData();Array.from(files).forEach(file=>fd.append('files',file));const x=await fetch('/api/admin/uploads',{method:'POST',body:fd});const j=await x.json();if(!x.ok)throw new Error(j.error||'Error al subir');const urls:string[]=j.urls||[];if(kind==='hero')set('hero_image',urls[0]||'');else set('gallery_images',[...(edit.gallery_images||[]),...urls])}catch(e:any){setError(e.message)}finally{setUploading(false)}}
  async function saveEdit(){setBusy(true);setError('');const x=await fetch(`/api/admin/raffles/${slug}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(edit)});const j=await x.json();setBusy(false);if(!x.ok){setError(j.error||'No se pudo guardar');return}setSaved(true);setTimeout(()=>setSaved(false),2500);if(j.raffle.slug!==slug){router.replace(`/admin/rifas/${j.raffle.slug}`);return}setR(j.raffle);setEdit(toEdit(j.raffle));load()}
  async function resetTests(){if(!confirm('¿Limpiar TODOS los apartados y pagos de prueba?'))return;const x=await fetch(`/api/admin/raffles/${slug}/test/reset`,{method:'POST'});const j=await x.json();if(!x.ok){alert(j.error||'No se pudieron limpiar las pruebas');return}await load();alert(`Pruebas limpiadas: ${j.cleared||0}`)}

  async function remove(){if(!confirm(`¿Eliminar definitivamente el borrador “${r.title}”?`))return;const x=await fetch(`/api/admin/raffles/${slug}`,{method:'DELETE'});const j=await x.json();if(!x.ok){alert(j.error||'No se pudo eliminar');return}router.push('/admin')}

  if(!r)return <main className="wrap"><div className="card">{error||'Cargando...'}</div></main>
  const revenue=stats.paid*r.price_cents,target=r.target_cents||r.total_numbers*r.price_cents

  return <main className="wrap">
    <div className="adminHeader"><div><span className="badge">{r.status}</span><h1>{r.title}</h1><p className="muted">/rifa/{r.slug}</p></div><div><a className="btn secondary" href="/admin">← Mis rifas</a> {r.status==='draft'?<><a className="btn secondary" href={`/admin/rifas/${slug}/preview`} target="_blank">👁 Vista previa</a><a className="btn" href={`/admin/rifas/${slug}/test`} target="_blank">🧪 Modo prueba</a></>:<a className="btn" href={`/rifa/${slug}`} target="_blank">Ver pública</a>}</div></div>

    {r.status==='draft'&&edit&&<>
      <div className="editorPreviewLayout">
        <section className="card editorPane">
          <h2>Editar borrador</h2><p className="muted">Los cambios se reflejan inmediatamente en la vista móvil. Guarda antes de abrir la vista previa completa.</p>
          <label>Título</label><input value={edit.title} onChange={e=>set('title',e.target.value)}/>
          <label>Slug (URL)</label><input value={edit.slug} onChange={e=>set('slug',e.target.value)}/>
          <label>Descripción</label><textarea value={edit.description} onChange={e=>set('description',e.target.value)}/>
          <div className="formGrid">
            <div><label>Meta MXN</label><input type="number" value={edit.target} onChange={e=>set('target',Number(e.target.value))}/></div>
            <div><label>Cantidad boletos</label><input type="number" value={edit.total_numbers} onChange={e=>set('total_numbers',Number(e.target.value))}/></div>
            <div><label>Precio boleto MXN</label><input type="number" disabled={autoPrice} value={edit.price} onChange={e=>set('price',Number(e.target.value))}/></div>
            <div><label>Valor premio MXN</label><input type="number" value={edit.value} onChange={e=>set('value',Number(e.target.value))}/></div>
            <div><label>Apartado minutos</label><input type="number" min="1" max="1440" value={edit.reserve_minutes} onChange={e=>set('reserve_minutes',Number(e.target.value))}/></div>
            <div><label>WhatsApp</label><input value={edit.whatsapp} onChange={e=>set('whatsapp',e.target.value)}/></div>
          </div>
          <label className="checkRow"><input type="checkbox" checked={autoPrice} onChange={e=>toggleAuto(e.target.checked)}/> Calcular precio automáticamente</label>
          <div className="calcBox"><div><span>Precio exacto</span><b>{moneyMx(exact)}</b></div><div><span>Precio recomendado</span><b>{moneyMx(recommended)}</b></div><div><span>Recaudación total</span><b>{moneyMx(projected)}</b></div></div>
          <div className="formGrid"><div><label>Apertura pública (opcional)</label><input type="datetime-local" value={edit.opens_at||''} onChange={e=>set('opens_at',e.target.value)}/></div><div><label>Cierre</label><input type="datetime-local" value={edit.closes_at} onChange={e=>set('closes_at',e.target.value)}/></div></div>
          <label>Entrega del premio</label><textarea value={edit.delivery_text} onChange={e=>set('delivery_text',e.target.value)} placeholder="Describe cómo y dónde se entregará el premio."/>
          <label>Bases y condiciones</label><textarea className="termsEditor" value={edit.terms_text} onChange={e=>set('terms_text',e.target.value)} placeholder="Escribe las bases que verá la persona participante antes de comprar."/>
          <label>Imagen principal</label><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload(e.target.files,'hero')}/>
          {edit.hero_image&&<div className="uploadPreview"><img src={edit.hero_image} alt="Principal"/><button className="tinyBtn danger" onClick={()=>set('hero_image','')}>Quitar</button></div>}
          <label>Galería</label><input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>upload(e.target.files,'gallery')}/>
          {(edit.gallery_images||[]).length>0&&<div className="uploadGrid">{edit.gallery_images.map((x:string,i:number)=><div key={x+i}><img src={x} alt={`Galería ${i+1}`}/><button className="tinyBtn danger" onClick={()=>set('gallery_images',edit.gallery_images.filter((_:string,n:number)=>n!==i))}>Quitar</button></div>)}</div>}
          {uploading&&<p className="notice">Subiendo imágenes...</p>}{error&&<p className="notice error">{error}</p>}
          <div className="stickyActions"><button className="btn" disabled={busy||uploading} onClick={saveEdit}>{busy?'Guardando...':saved?'✓ Cambios guardados':'Guardar cambios'}</button><a className="btn secondary" href={`/admin/rifas/${slug}/preview`} target="_blank">👁 Ver página completa</a></div>
        </section>
        <aside className="livePreviewPane"><div className="previewPhoneLabel">VISTA MÓVIL EN VIVO</div><div className="phoneFrame"><RafflePreview raffle={edit} compact/></div></aside>
      </div>
      <section className="card activationCard"><div><h2>Lista para publicar</h2><p className="muted">Revisa cada elemento antes de iniciar. Una rifa activa ya no puede editarse ni eliminarse.</p></div><div className="checklist">{checks.map(x=><div className={x.ok?'checkItem ok':'checkItem pending'} key={x.label}><span>{x.ok?'✓':'!'}</span>{x.label}</div>)}</div>{hasTestData&&<div className="testWarning"><b>🧪 Hay datos de prueba</b><span>{stats.testReserved} apartados · {stats.testPaid} pagados. Debes limpiarlos antes de activar.</span><button className="tinyBtn" onClick={resetTests}>Limpiar pruebas</button></div>}<div className="actions"><button className="btn danger" onClick={remove}>Eliminar rifa</button><a className="btn secondary" href={`/admin/rifas/${slug}/test`} target="_blank">🧪 Probar rifa</a><button className="btn" disabled={!canActivate||busy||uploading} onClick={()=>status('open',true)}>🚀 Iniciar rifa ahora</button></div>{!canActivate&&<p className="muted">{hasTestData?'Limpia las pruebas y completa la checklist antes de iniciar.':'Completa los elementos pendientes para habilitar el inicio.'}</p>}</section>
    </>}

    <div className="stats adminStats"><div className="stat"><b>{stats.available}</b><br/><span className="muted">disponibles</span></div><div className="stat"><b>{stats.reserved}</b><br/><span className="muted">apartados</span></div><div className="stat"><b>{stats.paid}</b><br/><span className="muted">pagados</span></div><div className="stat"><b>{money(revenue)}</b><br/><span className="muted">recaudado</span></div></div>{r.status==='draft'&&<section className="card testSummary"><div><span className="badge">MODO PRUEBA</span><h2>Simulaciones</h2><p className="muted">Estos registros no cuentan en la recaudación real.</p></div><div className="stats"><div className="stat"><b>{stats.testReserved}</b><br/><span className="muted">apartados prueba</span></div><div className="stat"><b>{stats.testPaid}</b><br/><span className="muted">pagados prueba</span></div></div><div className="actions"><a className="btn" href={`/admin/rifas/${slug}/test`} target="_blank">🧪 Abrir modo prueba</a>{hasTestData&&<button className="btn secondary" onClick={resetTests}>Limpiar pruebas</button>}</div></section>}
    <section className="card"><h2>Meta</h2><div className="progress"><div style={{width:`${target?Math.min(100,revenue/target*100):0}%`}}/></div><p>{money(revenue)} de {money(target)}</p><div className="actions">{r.status==='open'&&r.opens_at&&new Date(r.opens_at).getTime()>Date.now()&&<button className="tinyBtn" onClick={()=>status('open',true)}>Iniciar ahora</button>}{r.status==='open'&&<button className="tinyBtn danger" onClick={()=>status('closed')}>Cerrar rifa</button>}{r.status==='closed'&&<button className="tinyBtn" onClick={()=>status('open')}>Reabrir</button>}</div></section>
    {r.status==='closed'&&edit&&<section className="card"><h2>Programar reapertura</h2><p className="muted">Puedes cambiar solo las fechas antes de reabrir. Deja la apertura vacía para habilitar reservas inmediatamente al pulsar Reabrir.</p><div className="formGrid"><div><label>Nueva apertura (opcional)</label><input type="datetime-local" value={edit.opens_at||''} onChange={e=>set('opens_at',e.target.value)}/></div><div><label>Nuevo cierre (opcional)</label><input type="datetime-local" value={edit.closes_at||''} onChange={e=>set('closes_at',e.target.value)}/></div></div><div className="actions"><button className="btn" onClick={saveSchedule}>Guardar horario</button></div></section>}
    <section className="card"><div className="sectionHead"><div><h2>Vendedores y referidos</h2><p className="muted">Crea un enlace distinto para cada persona o campaña. Cuando se aparte un boleto, el origen queda guardado automáticamente.</p></div></div><div className="refCreate"><input value={refName} onChange={e=>setRefName(e.target.value)} placeholder="Nombre, ej. Ana"/><input value={refCode} onChange={e=>setRefCode(e.target.value)} placeholder="Código opcional, ej. ana"/><button className="btn" onClick={addReferral}>+ Crear enlace</button></div>{referrals.length===0?<p className="muted">Todavía no has creado enlaces personalizados.</p>:<div className="referralList">{referrals.map(x=><div className={`referralRow ${x.active?'':'inactive'}`} key={x.id}><div><b>{x.name}</b><div className="muted">?ref={x.code}</div></div><div className="referralMetrics"><span><b>{x.paid||0}</b> pagados</span><span><b>{x.reserved||0}</b> apartados</span></div><div className="actions"><button className="tinyBtn" disabled={!x.active} onClick={()=>copy(x.code)}>{copied===x.code?'✓ Copiado':'Copiar link'}</button><button className="tinyBtn secondary" onClick={()=>toggleReferral(x.id,!x.active)}>{x.active?'Pausar':'Activar'}</button><button className="tinyBtn danger" onClick={()=>deleteReferral(x.id,x.name)}>Eliminar</button></div></div>)}</div>}<p className="muted smallNote">Los enlaces de referido deben crearse aquí; los códigos no registrados no se atribuyen.</p></section>
    <section className="card tableWrap"><table className="adminTable"><thead><tr><th>#</th><th>Estado</th><th>Nombre</th><th>WhatsApp</th><th>Origen</th><th>Acciones</th></tr></thead><tbody>{rows.map(x=>{const p=part(x);return <tr key={x.id}><td><b>{String(x.number).padStart(2,'0')}</b></td><td>{x.status}{p?.is_test&&<span className="testPill">PRUEBA</span>}</td><td>{p?.name||'—'}</td><td>{p?.whatsapp||'—'}</td><td>{p?.referral||'—'}</td><td>{x.status==='reserved'?<><button className="tinyBtn" onClick={()=>action(x.number,'paid')}>Confirmar</button> <button className="tinyBtn danger" onClick={()=>action(x.number,'release')}>Liberar</button></>:x.status==='paid'?<button className="tinyBtn danger" onClick={()=>action(x.number,'release')}>Liberar</button>:'—'}</td></tr>})}</tbody></table></section>
  </main>
}
